# Generated by Django 3.0.7 on 2020-07-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200704_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
